### ISSUE TITLE
Getting AttributeError: type object  has no attribute '_query_cls' with fields.Nested and relationship

### ISSUE THREAD

**Issue by dolfandringa** [marshmallow-code/marshmallow-sqlalchemy#110]
Hi all,

I am getting an error when I am trying to create a new SQLAlchemy instance with a relationship defined. I am loading the new instance from JSON, and have a fields.Nested defined for the relationship attribute. But (I guess because of the relationship/ma-sa magic) the foreignkey field is not deserialized and can't be used to specify the id of the related instance, but when using the relationship attribute itself, it throws an error when sqlalchemy tries to query for the instance.

I may be doing something wrong myself, but don't know what. The documentation is quite sparse on this.

Here is a completely self contained example that throws the following error:
```
Traceback (most recent call last):
  File "app.py", line 60, in <module>
    terminal = TerminalSchema.loads(json.dumps(data))
  File "/usr/local/lib/python3.5/dist-packages/marshmallow/schema.py", line 603, in loads
    return self.load(data, many=many, partial=partial)
  File "/usr/local/lib/python3.5/dist-packages/marshmallow_sqlalchemy/schema.py", line 186, in load
    ret = super(ModelSchema, self).load(data, *args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/marshmallow/schema.py", line 580, in load
    result, errors = self._do_load(data, many, partial=partial, postprocess=True)
  File "/usr/local/lib/python3.5/dist-packages/marshmallow/schema.py", line 660, in _do_load
    index_errors=self.opts.index_errors,
  File "/usr/local/lib/python3.5/dist-packages/marshmallow/marshalling.py", line 295, in deserialize
    index=(index if index_errors else None)
  File "/usr/local/lib/python3.5/dist-packages/marshmallow/marshalling.py", line 68, in call_and_store
    value = getter_func(data)
  File "/usr/local/lib/python3.5/dist-packages/marshmallow/marshalling.py", line 288, in <lambda>
    data
  File "/usr/local/lib/python3.5/dist-packages/marshmallow/fields.py", line 265, in deserialize
    output = self._deserialize(value, attr, data)
  File "/usr/local/lib/python3.5/dist-packages/marshmallow/fields.py", line 465, in _deserialize
    data, errors = self.schema.load(value)
  File "/usr/local/lib/python3.5/dist-packages/marshmallow_sqlalchemy/schema.py", line 186, in load
    ret = super(ModelSchema, self).load(data, *args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/marshmallow/schema.py", line 580, in load
    result, errors = self._do_load(data, many, partial=partial, postprocess=True)
  File "/usr/local/lib/python3.5/dist-packages/marshmallow/schema.py", line 685, in _do_load
    original_data=data)
  File "/usr/local/lib/python3.5/dist-packages/marshmallow/schema.py", line 855, in _invoke_load_processors
    data=data, many=many, original_data=original_data)
  File "/usr/local/lib/python3.5/dist-packages/marshmallow/schema.py", line 957, in _invoke_processors
    data = utils.if_none(processor(data), data)
  File "/usr/local/lib/python3.5/dist-packages/marshmallow_sqlalchemy/schema.py", line 169, in make_instance
    instance = self.instance or self.get_instance(data)
  File "/usr/local/lib/python3.5/dist-packages/marshmallow_sqlalchemy/schema.py", line 155, in get_instance
    self.opts.model
  File "/usr/local/lib/python3.5/dist-packages/sqlalchemy/orm/session.py", line 1330, in query
    return self._query_cls(entities, self, **kwargs)
AttributeError: type object 'TerminalType' has no attribute '_query_cls'
```
with the following code:

```python
import json
from sqlalchemy import Column, Integer, Unicode, DateTime, Table, ForeignKey
from sqlalchemy import Numeric
from sqlalchemy.orm import relationship
from flask_sqlalchemy import SQLAlchemy
from marshmallow_sqlalchemy import ModelSchema
from flask import Flask
from flask_restful import Resource, Api
from flask import request
from marshmallow import fields

app = Flask(__name__)
app.config["SQLALCHEMY_DATABASE_URI"] = "sqlite://"
api = Api(app)
db = SQLAlchemy(app)

class TerminalType(db.Model):
    __tablename__ = 'terminaltypes'
    id = Column(Integer, primary_key=True)
    name = Column(Unicode, nullable=False)


class Terminal(db.Model):
    __tablename__ = 'terminals'
    id = Column(Integer, primary_key=True)
    name = Column(Unicode, nullable=False)
    terminaltypeid = Column(Integer, ForeignKey('terminaltypes.id'),
                            nullable=False)
    terminaltype = relationship("TerminalType", backref='terminals')

class _TerminalTypeSchema(ModelSchema):
    class Meta:
        model = TerminalType
        sqla_session = db.Session
    terminals = fields.Nested('_TerminalSchema', exclude=('terminaltype',))

class _TerminalSchema(ModelSchema):
    class Meta:
        model = Terminal
        sqla_session = db.Session
    terminaltype = fields.Nested(_TerminalTypeSchema, exclude=('terminals',))

TerminalSchema = _TerminalSchema()
TerminalTypeSchema = _TerminalTypeSchema()

ctx = app.app_context()
ctx.push()
db.create_all()
db.session.commit()

data = {'name': 'TestTType'}
ttype = TerminalTypeSchema.loads(json.dumps(data)).data
db.session.add(ttype)
db.session.commit()
print("\n%s" % ttype)
print("%i\n" % ttype.id)
#data = {'name':'TestTerminal', 'terminaltype':{'id': 1}}
#data = {'name':'TestTerminal', 'terminaltypeid': 1}
data = {'name':'TestTerminal', 'terminaltype':{'id': 1, 'name':'TestTType'}}
terminal = TerminalSchema.loads(json.dumps(data))
db.session.add(terminal.data)
db.session.commit()
```

**Comment by dolfandringa** [comment]
Ok, digging into it further, it turns out this has to do with ModelSchema.get_instance. It fails to fetch an existing object of terminaltype if the primary key (id) is specified as well as another field and raises the above mentioned error. But if I leave out the primary key like this:

```python
data = {'name':'TestTerminal', 'terminaltype':{'name': 'TestTType'}}
terminal = TerminalSchema.loads(json.dumps(data)).data
db.session.add(terminal)
db.session.commit()
print(terminal.terminaltype.id)
```

the error doesn't get raised, but instead it creates a new row in terminaltype (with id 2). This is also not desired. I want to refer to the existing row/instance, not create a new row. 

Specifying only the primary key like this:

```python
data = {'name':'TestTerminal', 'terminaltype':{'id': 1}}
terminal, errors = TerminalSchema.loads(json.dumps(data))
print(terminal)
print(errors)
if not errors:
    db.session.add(terminal.data)
    db.session.commit()
    print(terminal.terminaltype.id)
```

results in Marshmallow refusing to validate the data with the error: {'terminaltype': {'name': ['Missing data for required field.']}}. Indeed that field is required for a new row, but in this case I want to refer to an existing row, so the primary key should be enough.

So the question remains, how do I unmarshal data where a fields.Nested refers to a relationship with another existing entity. I don't see how I can do this and it feels like a bug to me, especially since when I use both id and name in the json dict, SQLAlchemy raises an error.

**Comment by dolfandringa** [comment]
I edited the above comment heavily to describe the problem more precisely. And as an addition, I am using sqlalchemy '1.1.9' and python 3.5.2

**Comment by sloria** [comment]
This may be fixed by using `marshmallow_sqlalchemy.fields.Nested` instead of `marshmallow.fields.Nested`. Closing for now, as this issue has gone stale. Feel free to comment if it's still an issue though
