### ISSUE TITLE
Do not support UUID type data save/load

### ISSUE THREAD

**Issue by thinksource** [marshmallow-code/marshmallow-sqlalchemy#147]
I try to use postgresql.UUID type as id:

my product json is:

```
{
  "id":"fceeec0d-de3c-4d65-84ff-f2374cf87e02",
  "name": "Iron Screwdriver",
  "provider":"ABC provider",
  "barcode":"e9099384-7e67-45e3-88d5-8b310b40d0aa",
  "price":10.5,
  "category_id":"a0b98a09-e7a4-4898-af70-7f3bd403678d"
}
```

I defined Product and ProductSchema like:

```
class Product(db.Model):
    __tablename__='Product'
    id = db.Column(postgresql.UUID, primary_key=True)
    name = db.Column(db.String(80), nullable=False)
    desc = db.Column(db.TEXT, nullable=True)
    provider = db.Column(db.String(200), nullable=False)
    barcode = db.Column(db.String(50), nullable=False)
    price = db.Column(db.DECIMAL(10, 2), nullable=False)
    category_id=db.Column(postgresql.UUID, db.ForeignKey('Category.id'))
    category = relationship("Category", back_populates='products')

    def __init__(self, **kwargs):
        super(Product, self).__init__(**kwargs)

class ProductSchema(ModelSchema):
    class Meta:
        model = Product
        sqla_session = db.session
        include_fk = True
```

I try to save this product use fellowing code:
```
def create(product):
    id = product.get('id')
    if not validate_uuid(id, 4):
        return uuid_error(obj,"id")
    existing_item = Product.query.filter(Product.id == id).one_or_none()
    if id is None:
        id = uuid.uuid4()
        product['id']=id
    if existing_item is None:
        schema = ProductSchema()
        new_item = schema.load(product, session=db.session).data    <<<<<< error happens here.
        print("==========================")

        db.session.add(new_item)
        db.session.commit()
        data = schema.dump(new_item).data
        return data, 201
```

My error is:

```
Traceback (most recent call last):
  File "F:\personalprojects\newrest\venv\lib\site-packages\flask\app.py", line 2309, in __call__
    return self.wsgi_app(environ, start_response)
  File "F:\personalprojects\newrest\venv\lib\site-packages\flask\app.py", line 2295, in wsgi_app
    response = self.handle_exception(e)
  File "F:\personalprojects\newrest\venv\lib\site-packages\flask\app.py", line 1741, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "F:\personalprojects\newrest\venv\lib\site-packages\flask\_compat.py", line 35, in reraise
    raise value
  File "F:\personalprojects\newrest\venv\lib\site-packages\flask\app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "F:\personalprojects\newrest\venv\lib\site-packages\flask\app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "F:\personalprojects\newrest\venv\lib\site-packages\flask\app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "F:\personalprojects\newrest\venv\lib\site-packages\flask\_compat.py", line 35, in reraise
    raise value
  File "F:\personalprojects\newrest\venv\lib\site-packages\flask\app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "F:\personalprojects\newrest\venv\lib\site-packages\flask\app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "F:\personalprojects\newrest\venv\lib\site-packages\connexion\decorators\decorator.py", line 73, in wrapper
    response = function(request)
  File "F:\personalprojects\newrest\venv\lib\site-packages\connexion\decorators\uri_parsing.py", line 117, in wrapper
    response = function(request)
  File "F:\personalprojects\newrest\venv\lib\site-packages\connexion\decorators\validation.py", line 163, in wrapper
    response = function(request)
  File "F:\personalprojects\newrest\venv\lib\site-packages\connexion\decorators\validation.py", line 336, in wrapper
    return function(request)
  File "F:\personalprojects\newrest\venv\lib\site-packages\connexion\decorators\decorator.py", line 44, in wrapper
    response = function(request)
  File "F:\personalprojects\newrest\venv\lib\site-packages\connexion\decorators\parameter.py", line 207, in wrapper
    return function(**kwargs)
  File "F:\personalprojects\newrest\api\product.py", line 23, in create
    new_item = schema.load(product, session=db.session).data
  File "F:\personalprojects\newrest\venv\lib\site-packages\marshmallow_sqlalchemy\schema.py", line 194, in load
    return super(ModelSchema, self).load(data, *args, **kwargs)
  File "F:\personalprojects\newrest\venv\lib\site-packages\marshmallow\schema.py", line 576, in load
    result, errors = self._do_load(data, many, partial=partial, postprocess=True)
  File "F:\personalprojects\newrest\venv\lib\site-packages\marshmallow\schema.py", line 683, in _do_load
    original_data=data)
  File "F:\personalprojects\newrest\venv\lib\site-packages\marshmallow\schema.py", line 863, in _invoke_load_processors
    data=data, many=many, original_data=original_data)
  File "F:\personalprojects\newrest\venv\lib\site-packages\marshmallow\schema.py", line 966, in _invoke_processors
    data = utils.if_none(processor(data), data)
  File "F:\personalprojects\newrest\venv\lib\site-packages\marshmallow_sqlalchemy\schema.py", line 176, in make_instance
    instance = self.instance or self.get_instance(data)
  File "F:\personalprojects\newrest\venv\lib\site-packages\marshmallow_sqlalchemy\schema.py", line 164, in get_instance
    **filters
  File "F:\personalprojects\newrest\venv\lib\site-packages\sqlalchemy\orm\query.py", line 2895, in first
    ret = list(self[0:1])
  File "F:\personalprojects\newrest\venv\lib\site-packages\sqlalchemy\orm\query.py", line 2687, in __getitem__
    return list(res)
  File "F:\personalprojects\newrest\venv\lib\site-packages\sqlalchemy\orm\query.py", line 2995, in __iter__
    return self._execute_and_instances(context)
  File "F:\personalprojects\newrest\venv\lib\site-packages\sqlalchemy\orm\query.py", line 3018, in _execute_and_instances
    result = conn.execute(querycontext.statement, self._params)
  File "F:\personalprojects\newrest\venv\lib\site-packages\sqlalchemy\engine\base.py", line 948, in execute
    return meth(self, multiparams, params)
  File "F:\personalprojects\newrest\venv\lib\site-packages\sqlalchemy\sql\elements.py", line 269, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)
  File "F:\personalprojects\newrest\venv\lib\site-packages\sqlalchemy\engine\base.py", line 1060, in _execute_clauseelement
    compiled_sql, distilled_params
  File "F:\personalprojects\newrest\venv\lib\site-packages\sqlalchemy\engine\base.py", line 1132, in _execute_context
    None, None)
  File "F:\personalprojects\newrest\venv\lib\site-packages\sqlalchemy\engine\base.py", line 1413, in _handle_dbapi_exception
    exc_info
  File "F:\personalprojects\newrest\venv\lib\site-packages\sqlalchemy\util\compat.py", line 265, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb, cause=cause)
  File "F:\personalprojects\newrest\venv\lib\site-packages\sqlalchemy\util\compat.py", line 248, in reraise
    raise value.with_traceback(tb)
  File "F:\personalprojects\newrest\venv\lib\site-packages\sqlalchemy\engine\base.py", line 1127, in _execute_context
    context = constructor(dialect, self, conn, *args)
  File "F:\personalprojects\newrest\venv\lib\site-packages\sqlalchemy\engine\default.py", line 695, in _init_compiled
    for key in compiled_params
  File "F:\personalprojects\newrest\venv\lib\site-packages\sqlalchemy\engine\default.py", line 695, in <genexpr>
    for key in compiled_params
  File "F:\personalprojects\newrest\venv\lib\site-packages\sqlalchemy\dialects\postgresql\psycopg2.py", line 448, in process
    value = _python_UUID(value)
  File "d:\anaconda3\Lib\uuid.py", line 138, in __init__
    hex = hex.replace('urn:', '').replace('uuid:', '')
sqlalchemy.exc.StatementError: (builtins.AttributeError) 'UUID' object has no attribute 'replace'
```

which is happens in UUID defination:

when initialize the UUID type:
uuid.py file is like:

```
    def __init__(self, hex=None, bytes=None, bytes_le=None, fields=None,
                       int=None, version=None):
   ....
```
the first hex should be string type rather than UUID type.
But if I use the marshmallow-sqlalchemy I mean when I execute schema.load(product, session=db.session) , it will automatically change the ID data into UUID type and then give me error

**Comment by mvanbaak** [comment]
Any idea how to get this fixed? I'm running into the same problem at the moment.

**Comment by sloria** [comment]
I don't have time to investigate this immediately, but I'd gladly review/merge a PR fixing this.

**Comment by asteinlein** [comment]
I came across this myself, but after investigating a bit I don't think this is a marshmallow issue AFAICS. I got it working by specifying `as_uuid=True` to the UUID column type, i.e.:

`category_id=db.Column(postgresql.UUID(as_uuid=True), db.ForeignKey('Category.id'))`

**Comment by sloria** [comment]
Thanks @asteinlein for posting the fix.
