### ISSUE TITLE
Converting all dumped keys to camelCase from snake_case

### ISSUE THREAD

**Issue by AbdealiLoKo** [marshmallow-code/marshmallow-sqlalchemy#149]
We use snake_case in our DB but the APIs we have need to be in camelCase
I am thinking of using https://github.com/okunishinishi/python-stringcase to convert all my field names to camel easily.

But, how can I do this with marshmallow-sqlalchemy so that all my fields will be automatically converted to camelCase when dump/load ?

**Comment by AbdealiLoKo** [comment]
I tried overriding my metaclass with
```
class MyModelSchemaMeta(type(ModelSchema)):

    @classmethod
    def get_declared_fields(mcs, klass, cls_fields, inherited_fields, dict_cls):
        declared_fields = super(type(ModelSchema), mcs).get_declared_fields(klass, cls_fields, inherited_fields, dict_cls)
        # Convert all field names to camelcase
        final_fields = dict_cls()
        for fname, fvalue in declared_fields.items():
            fvalue.attribute = fname
            final_fields[stringcase.camelcase(fname)] = fvalue
        return final_fields
```

But this causes an error with `type object 'Author' has no attribute 'publishedBooks'`
I was expecting it to use `published_books` to get the property from my sqlalchemy model

```
Traceback (most recent call last):
  File "venv/lib/python3.6/site-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "venv/lib/python3.6/site-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "venv/lib/python3.6/site-packages/flask/views.py", line 84, in view
    return self.dispatch_request(*args, **kwargs)
  File "venv/lib/python3.6/site-packages/flask/views.py", line 149, in dispatch_request
    return meth(*args, **kwargs)
  File "venv/lib/python3.6/site-packages/flask_apispec/annotations.py", line 118, in wrapped
    return wrapper(*args, **kwargs)
  File "venv/lib/python3.6/site-packages/flask_apispec/wrapper.py", line 34, in __call__
    return self.marshal_result(unpacked, status_code)
  File "venv/lib/python3.6/site-packages/flask_apispec/wrapper.py", line 58, in marshal_result
    dumped = schema.dump(unpacked[0])
  File "venv/lib/python3.6/site-packages/marshmallow/schema.py", line 455, in dump
    index_errors=self.opts.index_errors,
  File "venv/lib/python3.6/site-packages/marshmallow/marshalling.py", line 148, in serialize
    index=(index if index_errors else None),
  File "venv/lib/python3.6/site-packages/marshmallow/marshalling.py", line 79, in call_and_store
    value = getter_func(data)
  File "venv/lib/python3.6/site-packages/marshmallow/marshalling.py", line 143, in <lambda>
    getter = lambda d: field_obj.serialize(attr_name, d, accessor=accessor)
  File "venv/lib/python3.6/site-packages/marshmallow/fields.py", line 255, in serialize
    return self._serialize(value, attr, obj)
  File "venv/lib/python3.6/site-packages/marshmallow/fields.py", line 554, in _serialize
    return [self.container._serialize(each, attr, obj) for each in value]
  File "venv/lib/python3.6/site-packages/marshmallow/fields.py", line 554, in <listcomp>
    return [self.container._serialize(each, attr, obj) for each in value]
  File "venv/lib/python3.6/site-packages/marshmallow_sqlalchemy/fields.py", line 73, in _serialize
    for prop in self.related_keys
  File "venv/lib/python3.6/site-packages/marshmallow_sqlalchemy/fields.py", line 63, in related_keys
    return get_primary_keys(self.related_model)
  File "venv/lib/python3.6/site-packages/marshmallow_sqlalchemy/fields.py", line 54, in related_model
    return getattr(self.model, self.attribute or self.name).property.mapper.class_
AttributeError: type object 'Author' has no attribute 'publishedBooks'
```

At line54 I checked:
```
print(self.attribute)
return getattr(self.model, self.attribute or self.name).property.mapper.class_
```
And the attribute value is coming as `None`. But in `final_fields` the attribute is set correctly.

**Comment by Dunstrom** [comment]
I have also ran into this issue is there any interest for a added feature with for example a parameter to dump that makes the result to be in CamelCase? My solution have been to add a method with the @post_dump decorator that converts all the name but I don't feel that it is a optimal solution.

**Comment by AbdealiLoKo** [comment]
For what it's worth my current approach is to set an attribute in the ModelSchemaMeta:

```python
import marshmallow_sqlalchemy
from marshmallow_sqlalchemy import ModelSchema
import stringcase

class MyModelSchemaMeta(type(ModelSchema)):
    @classmethod
    def get_declared_fields(mcs, klass, cls_fields, inherited_fields, dict_cls):
        declared_fields = super(type(ModelSchema), mcs).get_declared_fields(
            klass, cls_fields, inherited_fields, dict_cls)

        # Convert all field names to camelCase automatically using attributes
        new_fields = dict_cls()
        for fname, fvalue in declared_fields.items():
            if fvalue is None:  # Happens if the field was excluded
                new_fields[stringcase.camelcase(fname)] = None
                continue
            if fvalue.attribute is None:
                fvalue.attribute = fname
            if isinstance(fvalue, fields.List):  # For ListField, the child needs to be told it's attribute too
                if isinstance(fvalue.container, Related):
                    if fvalue.container.attribute is None:
                        fvalue.container.attribute = fname
                    if marshmallow_sqlalchemy.__version__ < '0.14.2':
                        # NOTE: This is a temp monkey-patch for:
                        # https://github.com/marshmallow-code/marshmallow-sqlalchemy/issues/121
                        fvalue.get_value = super(fields.List, fvalue).get_value
            new_fields[stringcase.camelcase(fname)] = fvalue

        return new_fields

class MyModelSchema(ModelSchema, metaclass=MyModelSchemaMeta):
    pass
```

Only issue here is that when I specify `exclude` in my Meta, I need to use camelCase instead of snake_case.

**Comment by sloria** [comment]
This use case is now documented in marshmallow: https://marshmallow.readthedocs.io/en/latest/examples.html#inflection-camel-casing-keys

**Comment by copdips** [comment]
@sloria 

could you please provide an example ?
