### ISSUE TITLE
schema.load : TypeError: unhashable type: 'dict' when using deep nested dictionaries

### ISSUE THREAD

**Issue by svenfraeys** [marshmallow-code/marshmallow-sqlalchemy#245]
hello,
I am trying to use marshmallow to load a dict that contains model in a model in a model. (so deep nested )
but once it seems to bug out when reaching the lowest model which stays a dict.
so it throws a `TypeError: unhashable type: 'dict'` exception.

Underneath a full standalone working example that shows the problem I am having.

In this example you have a Project which contains Users and a User can hold Spoons.
The goal that I have is to make a model using the schema.load passing a dictionary containing a project dict which has a user dict and a spoon dict.

The expected result would be sqlalchemy models where the project module has a single user and a single spoon.

Am I missing something in my setup or is this feature not supported yet?
Cheers and thanks!
Sven

Code:
```
from flask import Flask
from flask_sqlalchemy import SQLAlchemy
from flask_marshmallow import Marshmallow

app = Flask(__name__)
app.config['SQLALCHEMY_DATABASE_URI'] = 'postgresql://postgres@127.0.0.1:5432/test_marshmallow'
app.config["SQLALCHEMY_TRACK_MODIFICATIONS"] = False

ma = Marshmallow(app)
db = SQLAlchemy(app)

class Project(db.Model):
    __tablename__ = 'project'
    has_namespace = True

    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.String(80), nullable=False)
    users = db.relationship("User", back_populates="project", foreign_keys="[User.project_id]")

class User(db.Model):
    __tablename__ = 'user'
    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.String(80), nullable=False)

    project_id = db.Column(db.Integer, db.ForeignKey('project.id'), nullable=False)
    project = db.relationship("Project", back_populates="users", foreign_keys=[project_id])

    spoons = db.relationship("Spoon", back_populates="user", foreign_keys="[Spoon.user_id]")

class Spoon(db.Model):
    __tablename__ = 'spoon'
    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.String(80), nullable=False)

    user_id = db.Column(db.Integer, db.ForeignKey('user.id'), nullable=True)
    user = db.relationship("User", back_populates="spoons", foreign_keys=[user_id])

class BaseSchema(ma.ModelSchema):
    class Meta:
        include_fk = True

class ProjectSchema(BaseSchema):
    class Meta(BaseSchema.Meta):
        model = Project

class UserSchema(BaseSchema):
    class Meta(BaseSchema.Meta):
        model = User

class SpoonSchema(BaseSchema):
    class Meta(BaseSchema.Meta):
        model = Spoon

project_schema = ProjectSchema()
data = {
    'name': 'hello',
    'users': [
        {
            'name': 'man1',
            'spoons': [
                {'name': 'spoon1'}
            ]
        }
    ]
}

# create db
# db.create_all()

# load schema
project = project_schema.load(data, session=db.session)
print(project.name)
```

Traceback:
```
Traceback (most recent call last):
  File "C:\Users\svenf\AppData\Local\Programs\Python\Python36\lib\site-packages\marshmallow_sqlalchemy\fields.py", line 109, in _deserialize
    self.session.query(self.related_model), value
  File "C:\Users\svenf\AppData\Local\Programs\Python\Python36\lib\site-packages\marshmallow_sqlalchemy\fields.py", line 140, in _get_existing_instance
    raise NoResultFound
sqlalchemy.orm.exc.NoResultFound: ()

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\dev\projects\basset9\test_marshmallow.py", line 71, in <module>
    project = project_schema.load(data, session=db.session)
  File "C:\Users\svenf\AppData\Local\Programs\Python\Python36\lib\site-packages\marshmallow_sqlalchemy\schema.py", line 216, in load
    return super(ModelSchema, self).load(data, *args, **kwargs)
  File "C:\Users\svenf\AppData\Local\Programs\Python\Python36\lib\site-packages\marshmallow\schema.py", line 684, in load
    data, many=many, partial=partial, unknown=unknown, postprocess=True
  File "C:\Users\svenf\AppData\Local\Programs\Python\Python36\lib\site-packages\marshmallow\schema.py", line 799, in _do_load
    unknown=unknown,
  File "C:\Users\svenf\AppData\Local\Programs\Python\Python36\lib\site-packages\marshmallow\schema.py", line 639, in _deserialize
    index=index,
  File "C:\Users\svenf\AppData\Local\Programs\Python\Python36\lib\site-packages\marshmallow\schema.py", line 483, in _call_and_store
    value = getter_func(data)
  File "C:\Users\svenf\AppData\Local\Programs\Python\Python36\lib\site-packages\marshmallow\schema.py", line 632, in <lambda>
    val, field_name, data, **d_kwargs
  File "C:\Users\svenf\AppData\Local\Programs\Python\Python36\lib\site-packages\marshmallow\fields.py", line 329, in deserialize
    output = self._deserialize(value, attr, data, **kwargs)
  File "C:\Users\svenf\AppData\Local\Programs\Python\Python36\lib\site-packages\marshmallow\fields.py", line 660, in _deserialize
    result.append(self.inner.deserialize(each, **kwargs))
  File "C:\Users\svenf\AppData\Local\Programs\Python\Python36\lib\site-packages\marshmallow\fields.py", line 329, in deserialize
    output = self._deserialize(value, attr, data, **kwargs)
  File "C:\Users\svenf\AppData\Local\Programs\Python\Python36\lib\site-packages\marshmallow_sqlalchemy\fields.py", line 114, in _deserialize
    return self.related_model(**value)
  File "<string>", line 4, in __init__
  File "C:\Users\svenf\AppData\Local\Programs\Python\Python36\lib\site-packages\sqlalchemy\orm\state.py", line 441, in _initialize_instance
    manager.dispatch.init_failure(self, args, kwargs)
  File "C:\Users\svenf\AppData\Local\Programs\Python\Python36\lib\site-packages\sqlalchemy\util\langhelpers.py", line 68, in __exit__
    compat.reraise(exc_type, exc_value, exc_tb)
  File "C:\Users\svenf\AppData\Local\Programs\Python\Python36\lib\site-packages\sqlalchemy\util\compat.py", line 153, in reraise
    raise value
  File "C:\Users\svenf\AppData\Local\Programs\Python\Python36\lib\site-packages\sqlalchemy\orm\state.py", line 438, in _initialize_instance
    return manager.original_init(*mixed[1:], **kwargs)
  File "C:\Users\svenf\AppData\Local\Programs\Python\Python36\lib\site-packages\sqlalchemy\ext\declarative\base.py", line 842, in _declarative_constructor
    setattr(self, k, kwargs[k])
  File "C:\Users\svenf\AppData\Local\Programs\Python\Python36\lib\site-packages\sqlalchemy\orm\attributes.py", line 268, in __set__
    instance_state(instance), instance_dict(instance), value, None
  File "C:\Users\svenf\AppData\Local\Programs\Python\Python36\lib\site-packages\sqlalchemy\orm\attributes.py", line 1321, in set
    new_values, old_collection, new_collection, initiator=evt
  File "C:\Users\svenf\AppData\Local\Programs\Python\Python36\lib\site-packages\sqlalchemy\orm\collections.py", line 790, in bulk_replace
    constants = existing_idset.intersection(values or ())
  File "C:\Users\svenf\AppData\Local\Programs\Python\Python36\lib\site-packages\sqlalchemy\util\_collections.py", line 615, in intersection
    result._members.update(self._working_set(members).intersection(other))
TypeError: unhashable type: 'dict'
[Finished in 1.9s]
```

**Comment by sloria** [comment]
By default, `relationship`s generate [`Related`](https://marshmallow-sqlalchemy.readthedocs.io/en/latest/api_reference.html#marshmallow_sqlalchemy.fields.Related) fields on the schema, which deserialize primary keys, not nested representations.

You can override this by using the `Nested` field.

```python
from flask import Flask
from flask_sqlalchemy import SQLAlchemy
from flask_marshmallow import Marshmallow
from marshmallow_sqlalchemy.fields import Nested

app = Flask(__name__)
app.config["SQLALCHEMY_DATABASE_URI"] = "sqlite:///:memory:"
app.config["SQLALCHEMY_TRACK_MODIFICATIONS"] = False

ma = Marshmallow(app)
db = SQLAlchemy(app)


class Project(db.Model):
    __tablename__ = "project"
    has_namespace = True

    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.String(80), nullable=False)
    users = db.relationship(
        "User", back_populates="project", foreign_keys="[User.project_id]"
    )


class User(db.Model):
    __tablename__ = "user"
    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.String(80), nullable=False)

    project_id = db.Column(db.Integer, db.ForeignKey("project.id"), nullable=False)
    project = db.relationship(
        "Project", back_populates="users", foreign_keys=[project_id]
    )

    spoons = db.relationship(
        "Spoon", back_populates="user", foreign_keys="[Spoon.user_id]"
    )


class Spoon(db.Model):
    __tablename__ = "spoon"
    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.String(80), nullable=False)

    user_id = db.Column(db.Integer, db.ForeignKey("user.id"), nullable=True)
    user = db.relationship("User", back_populates="spoons", foreign_keys=[user_id])


class SpoonSchema(ma.ModelSchema):
    class Meta:
        model = Spoon


class UserSchema(ma.ModelSchema):
    class Meta:
        model = User

    users = ma.List(Nested(SpoonSchema))


class ProjectSchema(ma.ModelSchema):
    class Meta:
        model = Project

    users = ma.List(Nested(UserSchema))


project_schema = ProjectSchema()
data = {"name": "hello", "users": [{"name": "man1", "spoons": [{"name": "spoon1"}]}]}

db.create_all()

# load schema
project = project_schema.load(data, session=db.session)
print("project:", project)
print("project.name:", project.name)
print("project.users:", project.users)
print("project.users[0].spoons", project.users[0].spoons)
print("project.users[0].spoons[0].name", project.users[0].spoons[0].name)
# project: <Project (transient 4516602512)>
# project.name: hello
# project.users: [<User (transient 4518070032)>]
# project.users[0].spoons [<Spoon (transient 4518070480)>]
# project.users[0].spoons[0].name spoon1
```

**Comment by svenfraeys** [comment]
Hello sloria,

Thanks for helping out
But it seems that when I use Nested it is raising Exceptions when used with `include_fk = True` feature which I was using in my example.

Now this happens:
marshmallow.exceptions.ValidationError: {'users': {0: {'project_id': ['Missing data for required field.']}}}

I simplified the code example to mimic the problem and pasted the traceback

I do not know if this would be expected behavior?

Thanks !
Sven

```
from flask import Flask
from flask_sqlalchemy import SQLAlchemy
from flask_marshmallow import Marshmallow
from marshmallow_sqlalchemy.fields import Nested


app = Flask(__name__)
app.config['SQLALCHEMY_DATABASE_URI'] = 'postgresql://postgres@127.0.0.1:5432/test_marshmallow'
app.config["SQLALCHEMY_TRACK_MODIFICATIONS"] = False

ma = Marshmallow(app)
db = SQLAlchemy(app)

class Project(db.Model):
    __tablename__ = 'project'
    has_namespace = True

    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.String(80), nullable=False)
    users = db.relationship("User", back_populates="project", foreign_keys="[User.project_id]")

class User(db.Model):
    __tablename__ = 'user'
    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.String(80), nullable=False)

    project_id = db.Column(db.Integer, db.ForeignKey('project.id'), nullable=False)
    project = db.relationship("Project", back_populates="users", foreign_keys=[project_id])

class UserSchema(ma.ModelSchema):
    class Meta:
        include_fk = True
        model = User

class ProjectSchema(ma.ModelSchema):
    class Meta:
        model = Project

    users = ma.List(Nested(UserSchema))
    

project_schema = ProjectSchema()
data = {
    'name': 'hello',
    'users': [
        {
            'name': 'man1',
        }
    ]
}

# create db
# db.create_all()

# load schema
project = project_schema.load(data, session=db.session)
# this raises
# marshmallow.exceptions.ValidationError: {'users': {0: {'project_id': ['Missing data for required field.']}}}
```
```
Traceback (most recent call last):
  File "C:\dev\projects\test_marshmallow.py", line 56, in <module>
    project = project_schema.load(data, session=db.session)
  File "C:\Users\svenf\AppData\Local\Programs\Python\Python36\lib\site-packages\marshmallow_sqlalchemy\schema.py", line 216, in load
    return super(ModelSchema, self).load(data, *args, **kwargs)
  File "C:\Users\svenf\AppData\Local\Programs\Python\Python36\lib\site-packages\marshmallow\schema.py", line 684, in load
    data, many=many, partial=partial, unknown=unknown, postprocess=True
  File "C:\Users\svenf\AppData\Local\Programs\Python\Python36\lib\site-packages\marshmallow\schema.py", line 842, in _do_load
    raise exc
marshmallow.exceptions.ValidationError: {'users': {0: {'project_id': ['Missing data for required field.']}}}
```

**Comment by sloria** [comment]
With `include_fk = True`, required fields are getting generated for FK fields like `project_id`. This probably isn't what you want, since the `load` input data in your example doesn't include those. If you want to include the FK fields in the dump output, you can explicitly declare them

```python
from marshmallow_sqlalchemy import field_for

class UserSchema(ma.ModelSchema):
    class Meta:
        model = User

    project_id = field_for(User, "project_id", dump_only=True)
``` 

Update: remove `include_fk`
