### ISSUE TITLE
marshmallow-sqlalchemy does not handle NULL foreign keys

### ISSUE THREAD

**Issue by sebschrader** [marshmallow-code/marshmallow-sqlalchemy#3]
marshmallow-sqlalchemy breaks if a column with for a foreign key is NULL/None.

Use the main example from project's description and insert a book without an author and try to serialize it.

``` python
>>> book = Book(title="Fight Club")
>>> session.add(book)
>>> session.commit()
>>> book_schema = BookSchema()
>>> book_schema.dump(book).data
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/shreyder/.virtualenvs/mtest/lib/python3.4/site-packages/marshmallow/schema.py", line 564, in dump
    **kwargs
  File "/home/shreyder/.virtualenvs/mtest/lib/python3.4/site-packages/marshmallow/marshalling.py", line 137, in serialize
    index=(index if index_errors else None)
  File "/home/shreyder/.virtualenvs/mtest/lib/python3.4/site-packages/marshmallow/marshalling.py", line 56, in call_and_store
    value = getter_func(data)
  File "/home/shreyder/.virtualenvs/mtest/lib/python3.4/site-packages/marshmallow/marshalling.py", line 131, in <lambda>
    getter = lambda d: field_obj.serialize(attr_name, d, accessor=accessor)
  File "/home/shreyder/.virtualenvs/mtest/lib/python3.4/site-packages/marshmallow/fields.py", line 221, in serialize
    return self._serialize(value, attr, obj)
  File "/home/shreyder/.virtualenvs/mtest/lib/python3.4/site-packages/marshmallow/fields.py", line 1180, in _serialize
    value = self.keygetter(value)
  File "/home/shreyder/.virtualenvs/mtest/lib/python3.4/site-packages/marshmallow_sqlalchemy/convert.py", line 18, in get_pk_from_identity
    _, key = identity_key(instance=obj)
  File "/home/shreyder/.virtualenvs/mtest/lib/python3.4/site-packages/sqlalchemy/orm/util.py", line 275, in identity_key
    mapper = object_mapper(instance)
  File "/home/shreyder/.virtualenvs/mtest/lib/python3.4/site-packages/sqlalchemy/orm/base.py", line 266, in object_mapper
    return object_state(instance).mapper
  File "/home/shreyder/.virtualenvs/mtest/lib/python3.4/site-packages/sqlalchemy/orm/base.py", line 288, in object_state
    raise exc.UnmappedInstanceError(instance)
sqlalchemy.orm.exc.UnmappedInstanceError: Class 'builtins.NoneType' is not mapped


```

**Comment by CaptObvious** [comment]
I'm also having this issue.  Did you find a workaround?
