### ISSUE TITLE
Invaid Syntax

### ISSUE THREAD

**Issue by andremvb** [marshmallow-code/marshmallow-sqlalchemy#304]
Hello! I am using python 2.7. And I get this error:

Traceback (most recent call last):
  File "/Users/Develop/PycharmProjects/testAPI/app.py", line 3, in <module>
    from flask_marshmallow import Marshmallow
  File "/Users/Develop/PycharmProjects/testAPI/venv/lib/python2.7/site-packages/flask_marshmallow/__init__.py", line 24, in <module>
    from . import sqla
  File "/Users/Develop/PycharmProjects/testAPI/venv/lib/python2.7/site-packages/flask_marshmallow/sqla.py", line 12, in <module>
    import marshmallow_sqlalchemy as msqla
  File "/Users/Develop/PycharmProjects/testAPI/venv/lib/python2.7/site-packages/marshmallow_sqlalchemy/__init__.py", line 1, in <module>
    from .schema import TableSchemaOpts, ModelSchemaOpts, TableSchema, ModelSchema
  File "/Users/Develop/PycharmProjects/testAPI/venv/lib/python2.7/site-packages/marshmallow_sqlalchemy/schema.py", line 101
    class TableSchema(ma.Schema, metaclass=TableSchemaMeta):
                                          ^
SyntaxError: invalid syntax

Process finished with exit code 1

I am using 0.19.0

**Comment by peterschutt** [comment]
Specifying metaclass with the `metaclass=...` keyword argument is a python3 thing: https://docs.python.org/3/whatsnew/3.0.html#changed-syntax.

Python 2.7 support was dropped from this lib in 0.19: https://github.com/marshmallow-code/marshmallow-sqlalchemy/issues/241. You'd have to pin to 0.18, but really you should use python 3 if you can.

**Comment by sloria** [comment]
As suggested above, you'll need to pin to 0.18 until you upgrade to Python 3.
