### ISSUE TITLE
Can't set auto_field properties for PostgreSQL.ARRAY: AttributeError for '__mro__'

### ISSUE THREAD

**Issue by mjpieters** [marshmallow-code/marshmallow-sqlalchemy#392]
For columns using the PostgreSQL `ARRAY` type, you can't set additional attributes with `auto_field()`. Because `convert._field_update_kwargs()` can't handle a *`functools.partial()` object* being passed in, the following MRE triggers an attribute error:

```python
from marshmallow_sqlalchemy.convert import field_for
from sqlalchemy import Column, Integer, String
from sqlalchemy.orm import declarative_base
from sqlalchemy.dialects.postgresql import ARRAY

Base = declarative_base()

class Foo(Base):
    __tablename__ = "foo"
    id = Column(Integer, primary_key=True)
    bar = Column(ARRAY(String))

field_for(Foo, "bar", dump_only=True)
```

Running this results in:

```python
Traceback (most recent call last):
  File "/tmp/mre.py", line 15, in <module>
    field_for(Foo, "bar", dump_only=True)
  File "/.../lib/python3.9/site-packages/marshmallow_sqlalchemy/convert.py", line 224, in field_for
    converted_prop = self.property2field(prop, **kwargs)
  File "/.../lib/python3.9/site-packages/marshmallow_sqlalchemy/convert.py", line 192, in property2field
    _field_update_kwargs(field_class, field_kwargs, kwargs)
  File "/.../lib/python3.9/site-packages/marshmallow_sqlalchemy/convert.py", line 63, in _field_update_kwargs
    for cls in inspect.getmro(field_class)
  File "/.../lib/python3.9/inspect.py", line 490, in getmro
    return cls.__mro__
AttributeError: 'functools.partial' object has no attribute '__mro__'
```

If you remove the `dump_only=True` argument to `auto_field()`, the exception doesn't occur. The same problem applies to using `auto_field()` on a `SQLAlchemyAutoSchema` subclass.

The workaround would be to unwrap the `partial` object: at the top of the `_field_update_kwargs` function:

```python
def _field_update_kwargs(field_class, field_kwargs, kwargs):
    if not kwargs:
        return field_kwargs
    
    if isinstance(field_class, functools.partial):
        # Unwrap partials, assuming that they bind a Field to arguments
        field_class = field_class.func

    possible_field_keywords = {
        key
        for cls in inspect.getmro(field_class)
        for key, param in inspect.signature(cls).parameters.items()
        if param.kind is inspect.Parameter.POSITIONAL_OR_KEYWORD
        or param.kind is inspect.Parameter.KEYWORD_ONLY
    }
    for k, v in kwargs.items():
        if k in possible_field_keywords:
            field_kwargs[k] = v
        else:
            _set_meta_kwarg(field_kwargs, k, v)
    return field_kwargs
```

**Comment by mjpieters** [comment]
We can work around this for now with a monkey-patch:

```python
from functools import partial, wraps

from marshmallow_sqlalchemy import convert


orig = convert._field_update_kwargs

@wraps(orig)
def unwrap_partial_field_update_kwargs(field_class, *args, **kwargs):
    if isinstance(field_class, partial):
        # Unwrap partials, assuming that they bind a Field to arguments
        field_class = field_class.func
    return orig(field_class, *args, **kwargs)

convert._field_update_kwargs = unwrap_partial_field_update_kwargs
```
